### ISSUE TITLE
[Nsfw] Bug report

### ISSUE THREAD

**Issue by theMisteryDE** [Onii-Chan-Discord/onii-cogs#57]
Hey man, kinda the same issue like was reported before. There are some commands who respond with the help menu and want <ctx> but whatever you try, there comes an error. I'm using your cog since july and have to admit, it worked best before you added hentai as a precommand.

I could recreate this with hentai and it's sub commands: anal, ass, boobs, pussy

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/lady_red/cogs/CogManager/cogs/nsfw/nsfw.py", line 284, in boobs
    if ctx.channel.is_nsfw():
AttributeError: 'str' object has no attribute 'channel'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 832, in invoke
    await super().invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1348, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'str' object has no attribute 'channel'

**Comment by theMisteryDE** [comment]
On one side I liked it when you added the group commands. So I could use malarne's oBoobs aswell, no double commands anymore. But I actually prefered the time before the group commands.

Well, that's just my opinion. Maybe more people like it the way it is.

**Comment by Onii-Chan-Discord** [comment]
A pr was made an hour before you commented, which should fix this issue! Would you mind updating your cog and trying it again?

**Comment by theMisteryDE** [comment]
Hey, sorry for the late reply. My timezone is UTC+2 and I was already in bed.

I just updated the cog and tested all commandy again. Glad to say they work now :)

**Comment by Onii-Chan-Discord** [comment]
Great to hear!

I'll be closing this Issue now.
